name: power_she_pre
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  google_fonts: ^3.0.1
  persistent_bottom_nav_bar_v2: ^4.2.6
  custom_line_indicator_bottom_navbar: ^0.0.8
  curved_nav_bar: ^0.0.2
  sidebarx: ^0.14.0
  image_picker: ^0.8.6
  modal_progress_hud_nsn: ^0.3.0
  tflite: ^1.1.2
  file_picker: ^5.2.4
  get: ^4.6.5
  country_code_picker: ^2.0.2
  firebase_database: ^10.0.9
  url_launcher: ^6.1.7
  youtube_player_flutter: ^8.1.2
  shared_preferences: ^2.0.15
  firebase_storage: ^11.0.10
  google_maps_flutter: ^2.2.3
  http: ^0.13.5
  lottie: ^2.1.0
  dartz: ^0.10.1
  flutter_riverpod: ^2.1.3
  fab_circular_menu: ^1.0.2
  flutter_polyline_points: ^1.0.0
  flutter_rating_stars: ^1.0.3+4
  flip_card: ^0.6.0
  flutter_dotenv: ^5.0.2
  step_progress_indicator: ^1.0.2
  location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_carousel_intro: ^0.0.9

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
  assets:
    - images/
    - assets/
    - assets/animassets/mapanimation.json
    - assets/mapicons/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Lustria
      fonts:
        - asset: fonts/Lustria-Regular.ttf

    - family: WorkSans
      fonts:
          - asset: fonts/WorkSans-Regular.ttf
          - asset: fonts/WorkSans-Italic.ttf
            style: italic
          - asset: fonts/WorkSans-Bold.ttf
            weight: 700
          - asset: fonts/WorkSans-SemiBold.ttf
            weight: 500
          - asset: fonts/WorkSans-Light.ttf
            weight: 200
          - asset: fonts/WorkSans-Thin.ttf
            weight: 300
          - asset: fonts/WorkSans-Medium.ttf
            weight: 400
          - asset: fonts/WorkSans-ExtraLight.ttf
            weight: 100
